### PR TITLE
Login page

### PR DESCRIPTION
**Pull request by frypan01**
#52

### CODE REVIEW

**Comment by frypan01** [comment]
Please review!

**Comment by xMrAfonso** [comment]
You basically broke the Main Page, it stills looks quite weird. The Login Page looks good, but can't accept it because of your changes to the main page. Next time, preferably make 2 separate PRs.

**Comment by frypan01** [comment]
Alright,I make a different PR .Thanks for review

**Comment by frypan01** [comment]
I hope it's all set

**Comment by xMrAfonso** [comment]
Thanks for fixing the issues! And thanks for your contribution.

**Pull request merged**
