### PR TITLE
Added Footer #59

### PR DESCRIPTION
**Pull request by anushkamandal25**
Hello! @surajondev Please check my pr.

### CODE REVIEW

**Comment by xMrAfonso** [comment]
Hi there! Could you just space the icons a little bit, it's a bit too close, besides that, it's perfect.

**Comment by anushkamandal25** [comment]
Is it okay now? Kindly check @xMrAfonso

**Comment by xMrAfonso** [comment]
Yes, thanks a lot!

**Comment by anushkamandal25** [comment]
Kindly add "hacktoberfest2022" and "hacktoberfest-accepted" tags @xMrAfonso @surajondev so that this contribution gets counted

**Pull request merged**
