### PR TITLE
Made go back button work and change avatar img as it was not working.

### PR DESCRIPTION
**Pull request by kumarsanu2002**

### CODE REVIEW

**Comment by kumarsanu2002** [comment]
@surajondev  merge it.

**Review by surajondev — APPROVED** [review]

**Comment by surajondev** [comment]
Thanks for the PR. The animation looks dope. It has been merged.

I will be glad if you can leave a star on this repository.

**Comment by kumarsanu2002** [comment]
@surajondev I have stared it . Let me know if I can add or improve anything

**Comment by surajondev** [comment]
Thanks for the PR. The animation looks dope. It has been merged.

I will be glad if you can leave a star on this repository.

**Comment by kumarsanu2002** [comment]
@surajondev bro you made mistake in merge whole alert section got messedup.

**Comment by surajondev** [comment]
Because of this PR?

**Comment by kumarsanu2002** [comment]
nope 
mine code is working fine

**Comment by surajondev** [comment]
Okay. Let me check

**Comment by kumarsanu2002** [comment]
ok let me know if i can make whole alert.html  pull request

**Pull request merged**
