### PR TITLE
Navigation bar added 

### LINKED ISSUE #120: Back button
Most of the designs lack the back button like image-slider, cards, forms, etc.
I would like to add the back button on every design page . 
This will make the site user friendly.
@surajondev Please assign this to me i want to work under HactoberFest 2023.

### PR DESCRIPTION
**Pull request by kanishka-parmar**
Navigation Bar Added ISSUE NO. #120 
Close #120

**Checklist:**

- I have mentioned the issue no.
- I have added the feature as discussed
- I have make sure that user can easily navigate .

### CODE REVIEW

**Comment by kanishka-parmar** [comment]
@surajondev Please look into this PR i am not getting why conflict is  coming in testimonialUi/index.html.

**Comment by kanishka-parmar** [comment]
@surajondev  Please look into this PR I have successfully added the navigation bar.

**Comment by surajondev** [comment]
Thanks for the PR. It has been merged.

**Comment by kanishka-parmar** [comment]
@surajondev hello can you please add the label HactoberFest accepted

**Pull request merged**
